### ISSUE TITLE
User-contributed recipes?

### ISSUE THREAD

**Issue by coatless** [R-macos/recipes#1]
@s-u,

@eddelbuettel & myself are looking to add a few libraries to the macOS build server. Would you accept user contributed recipes for [`mlpack`](http://www.mlpack.org/), [`libvw`](https://github.com/JohnLangford/vowpal_wabbit/wiki), and [`quantlib`](https://www.quantlib.org/)?

**Comment by s-u** [comment]
Absolutely! That was the whole point of this repo. Please submit a PR. Thanks.

**Comment by eddelbuettel** [comment]
Thanks for the prompt reply, we'll be in touch, probably starting with a vowpalwabbit library PR.

Where could I file tickets concerning CRAN builds on macOS?  I _really_ would like to backlist RcppAPT which has no chance of succeeding on macOS (no libapt) yet it still gets builds.  Can we change that?  Can we open a 'ticket system' or generalize `SystemRequirements`?  Would you prefer I open a Bugzilla bug?

**Comment by s-u** [comment]
Believe it or not, we don't actually have a way to blacklist a build :) Well, it can try, can it not? Maybe one day someone will write libapt for macOS ;)

**Comment by s-u** [comment]
But as for tickets - e-mail to me or `R-SIG-Mac` - that's pretty much it. I wouldn't mind if you simply raise an issue in this repo, that works for me, too, even if it's not a strictly official channel.

**Comment by eddelbuettel** [comment]
> Believe it or not, we don't actually have a way to blacklist a build

This [RcppAPT results page](https://cloud.r-project.org/web/checks/check_results_RcppAPT.html) would be a counter-example as BDR manages to skip the builds on Fedora.  I would be delighted if you could to.

**Comment by s-u** [comment]
There are many things BDR can do and I can't ;)

**Comment by s-u** [comment]
But I'll investigate and keep you posted. It doesn't matter if I build it or not - that's not really what you care about, you seem to care rather about the results page and that is out of my control so I have to ask.

**Comment by eddelbuettel** [comment]
I would appreciate that.  My only other recourse would be to add `configure` logic and make all functions "empty" and printing `no soup for you` in the case of non-suitable systems which, while fun, is still a waste of time.
