### ISSUE TITLE
fontconfig recipe fails to build

### ISSUE THREAD

**Issue by bas-dev** [R-macos/recipes#16]
When using the install script as indicated in the sibject header, I get the following errors at the end:

<Snippet/>
make[3]: *** No rule to make target `fcatomic.sgml', needed by `all'.  Stop.
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [fontconfig-2.13.93-dst] Error 2
</Snippet>

I'm using macOS 10.15.7 (19H524) on a MacBook Pro (16-inch, 2019). Please advise. Thnx.

**Comment by s-u** [comment]
Yes, thanks, this is a known issue in `fontconfig`: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/272

I have applied the fix listed above, but didn't include it in the recipe. I'll add a patch.
