### ISSUE TITLE
PR proposal: continuous integration tests

### ISSUE THREAD

**Issue by jeffreyhanson** [R-macos/recipes#17]
Hi,

Thank you very much for developing this project. I was wondering if I could please submit a PR to add continuous integration tests to this repository? Since I do not have access to a macOS computer, adding continuous integration tests would be really helpful for me to ensure that I do not waste your time by accidently submitting a broken PR when attempting to add a new dependency.

I noticed that the https://github.com/R-macos/recipes/tree/feature/actions branch has made some progress towards implementing these tests. May I ask what tasks remain to be completed before this branch can be merged? I would be happy to start addressing these remaining tasks if that's ok with you?

I am sorry if this information is already documented somewhere on the repository, or if I am wasting your time because it has previously been determined that such tests cannot be implemented.

**Comment by s-u** [comment]
@jeffreyhanson thanks, yes, I have created the branch specifically so you can fork it and run the tests you need. Building all the recipes would take forever so the idea is that you modify the action to run what you want to test.

**Comment by jeffreyhanson** [comment]
@s-u, thank you for getting back to me so quickly! Oh I see, thanks for clarifying that. I'll close this issue and start working on a PR for a new dependency.
