### ISSUE TITLE
gmp crashes on old hardware

### ISSUE THREAD

**Issue by jeroen** [R-macos/recipes#20]
```
> ### ** Examples
> 
>  S <- gmp::Stirling2(50,10)

 *** caught illegal operation ***
address 0x10ceadf6d, cause 'illegal opcode'

Traceback:
 1: as.bigz(0)
 2: S2(n1, k - 1)
 3: S2(n1, k - 1)
 4: S2(n1, k - 1)
 5: S2(n1, k - 1)
 6: S2(n1, k - 1)
 7: S2(n1, k - 1)
 8: S2(n1, k - 1)
 9: S2(n1, k - 1)
10: S2(n1, k - 1)
11: S2(n1, k - 1)
12: S2(n, k)
13: gmp::Stirling2(50, 10)
An irrecoverable exception occurred. R is aborting now ...
```

You need to pass a `--build` parameter to build for portable hardware instead of enabling optimizations for the current hardware, similar to homebrew here: https://github.com/Homebrew/homebrew-core/blob/565effc4ea7c0a2ead0d51c29fb5a86d45e5e8c6/Formula/gmp.rb#L48-L49

**Comment by s-u** [comment]
Can you provide more details? Which hardware in particular? Obviously, gmp is optimized which is intentional.

**Comment by jeroen** [comment]
It happens for example on GitHub / Azure VMs. 
Here is a minimal example: https://github.com/jeroen/testgmp
Log files: https://github.com/jeroen/testgmp/actions/runs/1296839202

This example simply runs the macos CRAN binary for the gmp package. Obviously, the same gmp binary package works fine on other hardware (e.g. the cran macbuilder or my local macbook), so the crash is hardware dependent.

I confirmed that this problem does not happen on GHA when we build the gmp R package from source using libgmp from homebrew or autobrew. So the issue really seems to be your libgmp. It likely has enabled some instructions that are available on your local hardware, but not on old/virtual hardware (which is exactly why homebrew uses the `--build` flag).

**Comment by s-u** [comment]
The missing information was that you are talking about running on non-Mac virtualized hardware on Azure as opposed to real Macs (ironically, virtualization on actual Macs doesn't have that problem since that what we use to build the binaries).

Looking at the MS docs is appears that Azure can run anything as old as Haswell and given the bug in some Skylake CPUs it means it is only safe to use as ancient setting as sandybridge. I'll check that compatibility.

**Comment by s-u** [comment]
Ok, sandy bridge seems fine. Checked with [gmp itself](https://github.com/s-u/gmp/runs/3778806656) and well as your [testgmp](https://github.com/s-u/testgmp/runs/3778833138) package test.

**Comment by jeroen** [comment]
Awesome! Thanks for the quick fix.

Btw, I think macos can only be virtualized on apple hardware (both legally and technically), I don't think non-mac virtualized hw exits, that is why it is so expensive for most cloud providers.

**Comment by jeroen** [comment]
Can you also rebuild the gmp binary package for R 4.0 please? Still getting the crashes for the gmp binary in r-oldrel...

**Comment by s-u** [comment]
Sure, rebuilt.
