### ISSUE TITLE
openssl 

### ISSUE THREAD

**Issue by DoaneAS** [R-macos/recipes#21]
Hi,

Executing `sudo ./build.sh r-base-dev` is returning an error compiling openssl:

```
../src/openssl-1.1.1l/crypto/rand/rand_unix.c:385:9: error: implicit declaration of function 'CCRandomGenerateBytes' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (CCRandomGenerateBytes(buf, buflen) == kCCSuccess)
        ^
1 error generated.
make[2]: *** [crypto/rand/rand_unix.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [openssl-1.1.1l-dst] Error 2
```

I'm on macOS 12.0.1, amd64 architecture, current Xcode (v 13.0) command line tools compilers.   All the other recipes up until openssl seem to be compiling and installing fine.  Any ideas?

thanks

**Comment by s-u** [comment]
Thanks, the last patch https://github.com/R-macos/recipes/commit/ad810bc88a15da5513d6b551bd8bcd835e97d859 fixed it for some systems but apparently broke it for others, so now in https://github.com/R-macos/recipes/commit/595f52e31e71d2c1a6b786c802ae866baa044627 I'm including both which should satisfy both new and old Xcode.

**Comment by jaganmn** [comment]
@s-u Somewhat relatedly: `sudo ./build.sh all` fails at apr-util, which seems to depend on openssl without having openssl listed as a dependency in `recipes/apr-util`. `sudo ./build.sh all` works after `sudo ./build.sh openssl`.

**Edit:** Spoke too soon. It fails again at netcdf whose source URL seems to be broken:

```lang-none
curl -L -o src/netcdf-c-4.7.4.tar.gz 'https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.7.4.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   226  100   226    0     0   1102      0 --:--:-- --:--:-- --:--:--  1102
100  8905  100  8905    0     0  21561      0 --:--:-- --:--:-- --:--:-- 1083k
mkdir -p src/netcdf-4.7.4 && (cd src/netcdf-4.7.4 && '/usr/bin/tar' fxj ../netcdf-c-4.7.4.tar.gz && mv */* . )
tar: Error opening archive: Unrecognized archive format
make: *** [src/netcdf-4.7.4] Error 1
```

Then:

```lang-none
$ file build/src/netcdf-c-4.7.4.tar.gz 
build/src/netcdf-c-4.7.4.tar.gz: HTML document text, ASCII text
```

After updating `recipes/netcdf` to use `https://downloads.unidata.ucar.edu/netcdf-c/4.8.1/netcdf-c-4.8.1.tar.gz`, `sudo ./build.sh all` fails at pango:

```lang-none
Configuring g-ir-scanner using configuration
Program g-ir-scanner found: YES (/Users/mikael/Desktop/R/recipes/build/pango-1.49.3-obj/subprojects/gobject-introspection/tools/g-ir-scanner)

subprojects/gobject-introspection/tools/meson.build:42:10: ERROR: Tried to override finding of executable "g-ir-scanner" which has already been found.
```

Stuck here...

**Comment by s-u** [comment]
@jaganmn thanks, the first two are fixed.

pango is always a pain, because the tools GTK uses are very buggy - I'd simply remove glibc and pango the from recipes, they tend to cause a lot of issues down the line as well so I don't build them on the production machines. I'll try to replicate it in the meantime.

**Comment by s-u** [comment]
@jaganmn sorry, I cannot reproduce it. On a clean macOS is works just fine. I would suspect that you may have some conflicting tools on the `PATH` like homebrew or similar. Make sure you remove everything from `/usr/local` before you start.

**Comment by jaganmn** [comment]
@s-u Thanks - I got things to work after cleaning up `/usr/local` (leaving, e.g., texlive alone) and removing Homebrew from my `PATH`. In the process I've noticed two more broken source URLs, in `recipes/udunits` and `other/tcltk/build-tktable.sh`. I replaced them with `https://downloads.unidata.ucar.edu/udunits/2.2.28/udunits-2.2.28.tar.gz` and `https://fossies.org/linux/privat/old/Tktable${VER}.tar.gz`.

**Comment by s-u** [comment]
@jaganmn Thanks for all the testing. It's annoying that some of the legacy projects are breaking their download links. The udunits one is actually correct, but it appears that UCAR servers are incredibly unreliable so I have created a [release on GitHub](https://github.com/s-u/UDUNITS-2/releases/tag/v2.2.28) to use a more reliable source.
