### ISSUE TITLE
Poppler missing font data

### ISSUE THREAD

**Issue by jeroen** [R-macos/recipes#27]
I see you added poppler recently, but in order to use this library, packages also need to ship a copy of the [poppler font data](https://poppler.freedesktop.org/poppler-data-0.4.11.tar.gz). See: https://poppler.freedesktop.org/

So if you want to force packages to use the local recipes build of poppler, you also have to supply a copy of this data and then insert that into the R binary package, similar to e.g. gdal and proj data.

**Comment by s-u** [comment]
Thanks, I have added `poppler-data`. Note that the package has to copy the data itself and make sure it can find it in the package binary - as you mentioned example packages that do that are `rgdal`, `sf` or `terra`.
