### ISSUE TITLE
Find pkg-config files under ./share

### ISSUE THREAD

**Issue by jeroen** [R-macos/recipes#28]
E.g `poppler-data.pc` from your [poppler-data-0.4.11-darwin.17-x86_64.tar.xz](https://mac.r-project.org/bin/darwin17/x86_64/poppler-data-0.4.11-darwin.17-x86_64.tar.xz) lives in `/usr/local/share/pkgconfig`.

I think you need this: https://github.com/r-devel/r-dev-web/pull/1/files

**Comment by s-u** [comment]
Thanks! Great catch! Now fixed in r5195 and also this catches issues with X11.
