### ISSUE TITLE
Can't find gfortran

### ISSUE THREAD

**Issue by josherrickson** [R-macos/recipes#29]
I'm seeing the following error upon package submission to the Mac Builder:

    make: /opt/R/arm64/bin/gfortran: No such file or directory

https://mac.r-project.org/macbuilder/results/1650654557-95b16b00edf9fa6f/

I apologize if this isn't the right place for the issue but this is the only place the R Mac Builder site directs to.

**Comment by s-u** [comment]
@josherrickson Thanks! I forgot to re-install Fortran after re-installing the tools for R 4.2.0, now fixed.

**Comment by josherrickson** [comment]
Great thanks for the fast fix!

**Comment by josherrickson** [comment]
@s-u I'm still getting this error. Does it take a while to propagate out?

**Comment by s-u** [comment]
@josherrickson No, it's immediate, but this was my bad - I installed Fortran but not the symlink from `/opt/R/arm64/bin`. Hopefully this I now truly fixed.
This actually raises an important issue that the symlink is not part of the tar ball, but hat's another story...

**Comment by josherrickson** [comment]
Terrific, works now. Thanks again.
