### ISSUE TITLE
Fatal error occured when compiling latest libpq on macOS Ventura 

### ISSUE THREAD

**Issue by yqy6611** [R-macos/recipes#34]
Hi all, 

I faced this fatal error when compiling latest libpq using recipe system, which never happened when installing previous one:

**fatal error: 'utils/errcodes.h' file not found**

Any ideas on how to fix it?

**Comment by s-u** [comment]
I saw that problem when I saw building with highly parallel `make` - re-running it with fewer jobs fixed it, so I thought it is just me or random. I suspect that postgress' makefiles are not specifying dependencies correctly and don't work well when built in parallel,. It may be worth reporting upstream, but I'll see if we can work around it during the build.

**Comment by yqy6611** [comment]
Thanks for your response! Besides, I found that latest binary files of gdal and proj contained one problems when compiling gdal-dedicated packages like terra : libproj or sqlite3 is not found. I can confirm that they have been installed. Errors never occurred when invoking previous versions of gdal/proj.

**Comment by s-u** [comment]
Did you install the pkg-config system stubs? The errors you describe sound like you are missing system dependencies in your pkg-config. The build.sh script puts them on PKG_CONFIG_PATH when building the recipes, but you have to either do it yourself or copy the stubs when building packages.

**Comment by yqy6611** [comment]
I have installed pkg-config yet the error still occured:


* installing *source* package ‘lwgeom’ ...
** package ‘lwgeom’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -arch arm64
configure: CXX: clang++ -arch arm64 -std=gnu++14
checking for gcc... clang -arch arm64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang -arch arm64 accepts -g... yes
checking for clang -arch arm64 option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for proj.h... yes
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj not found in standard or given locations.
ERROR: configuration failed for package ‘lwgeom’

**Comment by s-u** [comment]
See above - it's not about `pkg-config`, but the subs for system libraries. Apple no longer provides those, so you have to install them, they are in https://github.com/R-macos/recipes/tree/master/stubs/pkgconfig-darwin. As mentioned `build.sh` does that automatically: https://github.com/R-macos/recipes/blob/86cf6472c82269f2e3f8d3c004d4a6b7663d008a/build.sh#L128-L131 but if you are compiling packages, you have to do that yourself or you have to copy them to `/$PREFIX/lib/pkgconfig`.

**Comment by yqy6611** [comment]
OMG it works! Thanks Simon! BTW, may I report another two problems? URLs of sys-iodbc and mpfr are dead. Can you update them?
