### ISSUE TITLE
Can't restore time

### ISSUE THREAD

**Issue by coatless** [R-macos/recipes#36]
I'm attempting to setup an extraction directly inside of _R_ with `sudo` to avoid having to launch a separate _R_ session with `sudo`. 

Specifically, I'm using: 

```r
cmd = "sudo -kS curl -sSL https://mac.R-project.org/bin/darwin17/x86_64/xz-5.2.5-darwin.17-x86_64.tar.xz | tar fxj - -C /"
system(cmd, input = readline("Password:"))
```

I'm receiving:

```bash
usr/local/: Can't restore time
usr/local/pkg/: Can't create 'usr/local/pkg'
usr/local/pkg/xz-5.2.5-darwin.17-x86_64.list: Failed to create dir 'usr/local/pkg'
tar: Error exit delayed from previous errors.
```

This is using an intel (x86_64) mac. The issue appears to be similar to #11

**Comment by s-u** [comment]
@coatless you have `sudo` in the wrong place - you don't want to run `curl` as `root`, you want to run `tar` as root, so it's `sudo tar ...`. However, note that you cannot supply the password on `stdin` in that case as `curl` is already the `stdin`. You may be better off simply using `download.file()` instead and untar in a separate step.

That said, as a user I'd be horrified that you are asking for user password with echo, so I'd recommend relying on the system tools instead.

**Comment by coatless** [comment]
@s-u system is being used in this demo for an MVP. The full setup is given as: 

```r
shell_sudo_command = function(cmd, password, prefix = "sudo -kS ") {
    cmd_with_sudo = paste0(prefix, cmd)
    if (is.null(password)) {
        system(cmd_with_sudo, input = password_prompt("Enter user password to run command:"))
    } else {
        system(cmd_with_sudo, input = password)
    }
}

password_prompt = function(msg) {
    if(interactive()) {
        if(requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
            rstudioapi::askForPassword(msg)
        } else {
            readline(msg)
        }
    } else {
        stop("Unable to request password as the session is not being run interactively.")
    }
}
```

When possible, we'll accept the password via `rstudioapi::askForPassword()` prompt. Is there a better way of asking and storing a password using plain _R_? 

The goal here is to avoid exposing the user to terminal.

**Comment by s-u** [comment]
This is OT here, but fair enough - I'd just never allow echoed password entry no matter what, not even as fall-back. You can use `askpass::askpass()` which uses safe native entry regardless of the UI used.

**Comment by coatless** [comment]
Apologies for the off-topic component. I'll re-write using `askpass()`

Back on topic though, I'm still seeing the `Can't restore time` error: 

```r
# Download file
download.file(
    "https://mac.R-project.org/bin/darwin17/x86_64/xz-5.2.5-darwin.17-x86_64.tar.xz",
    "xz-5.2.5-darwin.17-x86_64.tar.xz"
)

# Install command
cmd = "sudo -kS tar fxj xz-5.2.5-darwin.17-x86_64.tar.xz -C /"
system(cmd, input = readline("Password:"))

# Password:usr/local/: Can't restore time
# tar: Error exit delayed from previous errors.
```

Or:

```r
download.file(
    "https://mac.R-project.org/bin/darwin17/x86_64/xz-5.2.5-darwin.17-x86_64.tar.xz",
    "xz-5.2.5-darwin.17-x86_64.tar.xz"
)

untar("xz-5.2.5-darwin.17-x86_64.tar.xz", exdir = "/")
```

Yields: 

```r
usr/local/: Can't restore time
usr/local/bin/: Can't restore time
usr/local/include/: Can't restore time
usr/local/lib/: Can't restore time
usr/local/pkg/: Can't restore time
usr/local/share/: Can't restore time
usr/local/share/doc/: Can't restore time
usr/local/share/man/: Can't restore time
usr/local/share/man/man1/: Can't restore time
```

**Comment by s-u** [comment]
One comment on the process there - note that even `root` is not guaranteed to have access to user's files (on macOS places like `Documents`, `Download` etc. are not readable even by `root`), so you want to make sure if you download the file you do so into `tempdir()`.

**Comment by s-u** [comment]
The above is expected, on macOS not even root can change the attributes of `/usr/local`. It is just a note, not an error. You can avoid it by not extracting outside of the prefix (as was illustrated in the issue you quoted: https://github.com/R-macos/recipes/commit/b060377a444bfa631ba93e9e4d88a55bfe10dec7).

**Comment by coatless** [comment]
Still observing a similar issue even with the modifications into `tempdir()` and adding the `--strip 2` option.

```r
save_location = file.path(tempdir(), "gdal-3.4.2-darwin.17-x86_64.tar.xz")
download.file(
    "https://mac.R-project.org/bin/darwin17/x86_64/gdal-3.4.2-darwin.17-x86_64.tar.xz",
    save_location
)
untar(save_location, exdir = "/usr/local", extras = "--strip 2")
```

Switching to a different package, e.g. `gdal` gives: 


```
bin/: Can't restore time
include/: Can't restore time
lib/: Can't restore time
pkg/: Can't restore time
share/: Can't restore time
share/gdal/: Can't create 'share/gdal'
share/gdal/bag_template.xml: Failed to create dir 'share/gdal'
share/gdal/cubewerx_extra.wkt: Failed to create dir 'share/gdal'
share/gdal/default.rsc: Failed to create dir 'share/gdal'
share/gdal/ecw_cs.wkt: Failed to create dir 'share/gdal'
share/gdal/eedaconf.json: Failed to create dir 'share/gdal'
share/gdal/epsg.wkt: Failed to create dir 'share/gdal'
share/gdal/esri_StatePlane_extra.wkt: Failed to create dir 'share/gdal'
share/gdal/gdalicon.png: Failed to create dir 'share/gdal'
share/gdal/GDALLogoBW.svg: Failed to create dir 'share/gdal'
```

Command output:

```r
'/usr/bin/tar -xf '/var/folders/b0/vt_1hj2d6yd8myx9lwh81pww0000gn/T//RtmpYvXNkT/gdal-3.4.2-darwin.17-x86_64.tar.xz' -C '/usr/local' --strip 2' returned error code 1
```

**Comment by s-u** [comment]
I think you missed `sudo` here?

**Comment by coatless** [comment]
@s-u yes, `untar()` doesn't seem to have that option.

With `sudo` present, everything worked beautiful. I settled on:  

```r
package_url = "https://mac.R-project.org/bin/darwin17/x86_64/xz-5.2.5-darwin.17-x86_64.tar.xz"
save_location = file.path(tempdir(), basename(package_url))
download.file(
    package_url,
    save_location
)

cmd = paste0("sudo -kS tar fxj ", save_location," -C /usr/local/ --strip 2")
system(cmd, input = askpass::askpass())
```

Thanks again for the help!
