### ISSUE TITLE
Error with freetype

### ISSUE THREAD

**Issue by jogiles** [R-macos/recipes#40]
Hello!

I am the following commands:
git clone https://github.com/R-macos/recipes.git
cd recipes
./build.sh r-base-dev

After running for several minutes, this was the output ( and error):
mkdir -p src/freetype-2.13.0 && (cd src/freetype-2.13.0 && '/usr/bin/tar' fxj ../freetype-2.13.0.tar.xz && mv */* . )
tar: Error opening archive: Unrecognized archive format
make: *** [src/freetype-2.13.0] Error 1

I am using Ventura 13.3.1 (Apple M1 Max).

Any help would be greatly appreciated!
 
Thank you! Josephine

**Comment by s-u** [comment]
This typically means that the source download failed. Remove the source with something like

    rm -rf build/src/freetype-*

and try again. GNU uses mirror re-directs so it's possible that you got a bad mirror or bad connection.

**Comment by jogiles** [comment]
Thank you for the prompt response! 
I deleted the entire recipe directory and did these steps again -- worked!

git clone https://github.com/R-macos/recipes.git
cd recipes
./build.sh r-base-dev
