### ISSUE TITLE
SQL headers clobbering

### ISSUE THREAD

**Issue by detule** [R-macos/recipes#41]
Hi Simon:

I was looking into some [deprecation warnings](https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/odbc-00check.html) that are thrown by the ODBC API: I could be wrong about this but I think the generic ODBC API headers, for example, `../include/sql.h` (and friends) are overwritten when both the `sys-iodbc` and `unixodbc` recipes are installed.

I noticed this because I think the deprecation warnings are in one set of headers (`iodbc`) but not in the other.  Any ideas on how to resolve this? 

You are not asking, but I would be happy if the `unixodbc` headers clobbered over the `sys-iodbc` rather than what looks like is the other way around. :)

Thanks again - and apologies if my intuition is way off as to why those deprecation warnings are thrown.

**Comment by detule** [comment]
Hi @s-u 

Have you given this some thought? This is causing issues for `package:odbc`, which expects to link against headers provided by `unixODBC` ( and there are material differences between those provided by `iODBC` versus `unixODBC` ).

In particular users are reporting major issues with the binary / CRAN version of the package ( beyond just the deprecation warnings ).

I guess there are couple of options:
* Make the `unixODBC` recipe "depend" on `sys-iodbc`.  I assume that might work?
* Install them in different sub-folders, perhaps?

Let me know if there is some way I can help / test / contribute recipe changes.

Thanks!

**Comment by s-u** [comment]
@detule yes, this is a problem - we can't really have both at the same time. There is really no order since we shouldn't have two package overwriting each other - we don't allow alternatives. As it stands now the behavior is undefined. I don't use ODBC myself - is there any reason to NOT use `unixodbc`?

**Comment by detule** [comment]
@s-u

Not aware of any ( reasons to NOT use `unixODBC` ).

**Comment by detule** [comment]
Fixed in https://github.com/R-macos/recipes/issues/48
