### ISSUE TITLE
Cannot compile lz4

### ISSUE THREAD

**Issue by yqy6611** [R-macos/recipes#47]
Hi all, 

I encountered this issue when tying to install lz4:

Install args: install DESTDIR=$(DESTDIR) prefix=/opt/R/arm64 BUILD_SHARED=no BUILD_STATIC=yes
Copying sources ...
mv: cannot stat '/Users/abcdefg/recipes/build/lz4-1.9.4-obj/Makefile': No such file or directory
Makefile generated.
make -f Makefile.real prefix=/opt/R/arm64 BUILD_SHARED=no BUILD_STATIC=yes lib-release
make: Makefile.real: No such file or directory
make: *** No rule to make target `Makefile.real'.  Stop.
make: *** [all] Error 2
make: *** [lz4-1.9.4-dst] Error 2

Any solutions? Many thanks!

**Comment by s-u** [comment]
Cannot replicate.  Make sure you have all necessary tools. If in doubt, post the full output.
