### ISSUE TITLE
Do I have to disable SIP in order to test?

### ISSUE THREAD

**Issue by shrektan** [R-macos/recipes#5]
Sorry to bother. My question may be silly. If so, please forgive my ignorance. In simple:

Can we change `sudo $(TAR) fxz '$^' -C / && touch '$@'` to something like below, so that we don't need to disable SIP for testing?

```
rm -fr ./tmp && mkdir ./tmp && sudo $(TAR) fxz '$^' -C ./tmp && sudo cp -r ./tmp/usr/local/ /usr/local/ && touch '$@'
```  

### Details

According to the comment from #2 

> That said, the error you see is because you have macOS with SIP (system integrity protection) enabled, so it won't allow you to change permissions on some directories. You can check, but I think it is benign because tar will untar and set permissions on files it can touch.

Yes, I know `sudo $(TAR) fxz '$^' -C / && touch '$@'` requires the permission.

However, from [About System Integrity Protection on your Mac](https://support.apple.com/en-us/HT204899),

> Paths and apps that third-party apps and installers can continue to write to include:
> - /Applications
> - /Library
> - /usr/local

Apparently, `/usr/local` is allowed to write. Will any library be installed to a directory other than `/usr/local`? In my limited experience, most of the library (if not all) are installed into `/usr/local`... If my statement is correct, the change I proposed should work, correct?

Thanks.

**Comment by coatless** [comment]
@shrektan I would spin up a macOS VM and make the SIP change there.

**Comment by shrektan** [comment]
@coatless Thanks for your suggestion. I do not have any experience on setting up a macOS VM but it seems a little bit heavy for some simple testing... Anyway, I will appreciate if you can share some experience regarding to spinning up a macOS VM...

**Comment by s-u** [comment]
You don't need to change SIP (and I would not advise to do so!), even with SIP you're still allowed to write in `/usr/local/` the warning from tar is merely that you cannot change attributes of the parent directory with is ok as we don't want that to change.

**Comment by shrektan** [comment]
Thanks for the reply. 

I can’t remember what exactly happened but I believe it’s an error rather than a warning. 

Anyway I’ve had a solution so I’m ok with closing the issue.

**Comment by s-u** [comment]
I have changed the default to `-C /usr/ --strip 1` so `tar` shouldn't try to modify `/usr`
