### ISSUE TITLE
lz4 binary missing for arm64

### ISSUE THREAD

**Issue by jeroen** [R-macos/recipes#50]
For intel there is [lz4-1.9.4-darwin.20-x86_64.tar.xz](https://mac.r-project.org/bin/darwin20/x86_64/lz4-1.9.4-darwin.20-x86_64.tar.xz) but no lz4 on: https://mac.r-project.org/bin/darwin20/arm64/

Also dependents zstd and bsdtar have not been updated.

**Comment by s-u** [comment]
Thanks, I believe this is now fixed.
