### ISSUE TITLE
"Packages not available" Error on R Mac Builder (Development)

### ISSUE THREAD

**Issue by jhorzek** [R-macos/recipes#53]
Hi,

Thank you very much for setting up the R Mac Builder! Unfortunately, I am currently running into issues when submitting a package to the development version of R. The errors are:

```
Packages required but not available: 'OpenMx', 'Rcpp', 'dplyr'

Packages suggested but not available for checking:
  'testthat', 'lavaan', 'knitr', 'rmarkdown'

VignetteBuilder package required for checking but not installed: ‘knitr’
```

However, the Build Log states:

```
NOTE: there is no source for package OpenMx [OpenMx], installed CRAN version will be used.
NOTE: there is no source for package testthat [testthat], installed CRAN version will be used.
NOTE: there is no source for package lavaan [lavaan], installed CRAN version will be used.
NOTE: there is no source for package knitr [knitr], installed CRAN version will be used.
NOTE: there is no source for package rmarkdown [rmarkdown], installed CRAN version will be used.
NOTE: there is no source for package Rcpp [Rcpp], installed CRAN version will be used.
NOTE: there is no source for package dplyr [dplyr], installed CRAN version will be used.
NOTE: there is no source for package Rcpp [Rcpp], installed CRAN version will be used.
```
That is, the packages should be installed, but seem to not be found when running the checks. When submitting the same package to the release version of R Mac Builder, the checks run correctly.

To reproduce the errors, you can upload the [latest version of mxsem from CRAN](https://cran.r-project.org/src/contrib/Archive/mxsem/).

Best,
Jannik

**Comment by s-u** [comment]
Please note that it is expected as there are no CRAN binaries of those packages for R-devel (we only build R-devel packages closer to the release due to resource constraints) - see CRAN.

Also please note that this repository is about the build recipes and not the Mac Builder service so please contract me (or R-SIG-Mac) by email instead in the future.

**Comment by jhorzek** [comment]
Thank you for clarifying and sorry for asking in the wrong channel!
