### ISSUE TITLE
Cannot detect gdal on macOS Sequira system

### ISSUE THREAD

**Issue by yqy6611** [R-macos/recipes#56]
Hi, 

After upgrading my macOS to sequira, I found that R cannot detect gdal in /opt/R/arm64. Like this:

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -arch arm64
configure: CXX: clang++ -arch arm64 -std=gnu++17
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’

However, gdal is actually there. 

May I learn how to solve it? Many thanks!

**Comment by jeroen** [comment]
You probably need to add `/opt/R/arm64/bin` to your $PATH (if that is where `gdal-config` is).

**Comment by yqy6611** [comment]
Yes it works. Thanks.
