### ISSUE TITLE
GSOC + Boost Headers?

### ISSUE THREAD

**Issue by coatless** [R-macos/recipes#8]
@s-u would it be possible to potentially have a student work on creating recipes for different kinds of libraries for Google Summer of Code (GSOC)? 

Also, may we assume that boost headers are installed on the CRAN box? Or would this require a recipe to be created and applied?

**Comment by s-u** [comment]
Sure, absolutely. If we go that way, I'd recommend unifying all the approaches that exists so we agree on one system and not have different path for each platform. That sounds like a good GSoC project.

As for Boost headers - I thought that was already provided by the BH package? But, yes, if you want that as a system dependency instead, it has to be a recipe, only standard macOS + Xcode should be assumed as far as dependencies go.

**Comment by coatless** [comment]
@s-u Thanks for the response.

> Sure, absolutely. If we go that way, I'd recommend unifying all the approaches that exists so we agree on one system and not have different path for each platform. That sounds like a good GSoC project.

I'll write up a proposal. My ideas for a student to potential implement are:
 
- Improvements to the compiled code setup for macOS
- Creating additional documentation for `recipes`
- Building new `recipes` for libraries.

Would you be okay with acting as a second mentor or auxiliary mentor for the proposal?

Also, is there a preferred way to contact you to review the proposal? (@r-project.org or @att.net ? ) 

> As for Boost headers - I thought that was already provided by the BH package? But, yes, if you want that as a system dependency instead, it has to be a recipe, only standard macOS + Xcode should be assumed as far as dependencies go.

Due to the way Boost is constructed, there are certain portions of the code base that cannot be placed into the `BH` package due to the necessity of building a library. For certain software libraries that we're interested in on-boarding -- such as [`vowpalwabbit`](https://github.com/VowpalWabbit/vowpal_wabbit), [`quantlib`](https://www.quantlib.org/) and [`mlpack`](https://github.com/mlpack/mlpack) -- we _must_ have a system installation of Boost due to the way the libraries are constructed.

**Comment by s-u** [comment]
See #6 for boost headers - it is now supported. Analogous process could be used for boost libraries.

Sure, yes, use R-project.org.
